### ISSUE TITLE
xTB parameter in DFT.QS section

### ISSUE THREAD

**Issue by xiki-tempula** [SINGROUP/pycp2k#12]
If one would like to use GFN1-xTB

```
    &QS
      METHOD xTB
      &xTB
        CHECK_ATOMIC_CHARGES F #xTB calculation often crashes without setting this to false
        &PARAMETER
          DISPERSION_PARAMETER_FILE dftd3.dat
          PARAM_FILE_NAME xTB_parameters
        &END PARAMETER
      &END xTB
    &END QS
```

The xTB attribute is not present in CP2K.CP2K_INPUT.FORCE_EVAL.DFT.QS.

**Comment by lauri-codes** [comment]
Hi @xiki-tempula,

Do you know in which CP2k version the xTB method was added in? Our pip package currently only targets CP2K 5.1 or older (I guess we should update it...)

If you want to build against a newer version, you can use the [manual installation method](https://github.com/SINGROUP/pycp2k#4-manual-installation).

**Comment by xiki-tempula** [comment]
@lauri-codes I see. I'm using version 8.1. Thanks.
