### ISSUE TITLE
Suggestion for syntax check

### ISSUE THREAD

**Issue by burbanom** [SINGROUP/pycp2k#2]
I have been using this package quite a bit lately and I find it extremely useful. I have recently come across a minor issue whenever I wish to restart a calculation from a previous one using an external restart file. I solved it by modifying line 291 to 

if "SUCCESS" not in syntax_result:

This problem originates in the output that cp2k gives if you do a syntax check when restarting from an external file. In this case the first 7 characters are not "SUCCESS" but instead cp2k prints information about the quantities that will be restarted, which means that the current test 

if syntax_result[0:7] != "SUCCESS":

fails even if there is no problem with the input file.

**Comment by lauri-codes** [comment]
Hi!

Very nice to hear that you find the package useful.

Thank you for reporting about this bug. It should now be fixed in the master branch. If you still have any problems with this, just send a new message.
