### ISSUE TITLE
Pls help!!! what is  wrong with pycp2k  run  

### ISSUE THREAD

**Issue by Greenlobby** [SINGROUP/pycp2k#6]
I have installed pycp2k in  Ubuntu  successfully,  and can run the examples included .   But I can not run my python format input file . PLs help me to find out what is wrong with the input. The corresponding CP2K format input  can be run    The following  is  the input.  and  the error  messages :

from pycp2k import CP2K

#===============================================================================
# Setup calculator
calc = CP2K()
calc.working_directory = "./"
calc.project_name = "H2O_py3"
calc.mpi_n_processes = 4

#===============================================================================
# Create shortcuts for the most used subtrees of the input.
CP2K_INPUT = calc.CP2K_INPUT
GLOBAL = CP2K_INPUT.GLOBAL
FORCE_EVAL = CP2K_INPUT.FORCE_EVAL_add()
SUBSYS = FORCE_EVAL.SUBSYS
MOTION = CP2K_INPUT.MOTION
DFT = FORCE_EVAL.DFT
FORCEFIELD = FORCE_EVAL.MM.FORCEFIELD

GLOBAL.Run_type = "GEO_OPT"
GLOBAL.Print_level = "LOW"

FORCE_EVAL.Method = "QuickStep"

DFT.Basis_set_file_name = "/home/dell/Softrun/cp2k-6.1/GTH_BASIS_SETS"
DFT.Potential_file_name = "/home/dell/Softrun/cp2k-6.1/GTH_POTENTIALS"
DFT.MGRID.Cutoff = 250
DFT.SCF.Eps_scf = 1.0E-6
DFT.XC.XC_FUNCTIONAL = "BLYP"
DFT.XC.XC_GRID.Xc_smooth_rho = "NN10"

SUBSYS.CELL.Abc = [15.0,15.0,15.0]
SUBSYS.COORD.Default_keyword = [["O",0,0,0],["H",0.7,0.7,0], ["H",-0.7,0.7,0]]
h_kind = SUBSYS.KIND_add("H")
h_kind.Basis_set = "TZVP-GTH"
h_kind.Potential = "GTH-BLYP-q1"

h_kind =SUBSYS.KIND_add("O")
h_kind.Basis_set =  "TZVP-GTH"
h_kind.Potential = "GTH-BLYP-q6"

#calc.write_input_file()

calc.run()

---------------------------------------------------------------------------
The  following  is  the error messages:

 >> CP2K version check...
  >> Creating CP2K input file...
Traceback (most recent call last):
  File "h2o.py", line 47, in <module>
    calc.run()
  File "/usr/local/lib/python3.7/site-packages/pycp2k-0.2.1-py3.7.egg/pycp2k/cp2k.py", line 288, in run
    self.write_input_file()
  File "/usr/local/lib/python3.7/site-packages/pycp2k-0.2.1-py3.7.egg/pycp2k/cp2k.py", line 251, in write_input_file
    input_file.write(self.get_input_string())
  File "/usr/local/lib/python3.7/site-packages/pycp2k-0.2.1-py3.7.egg/pycp2k/cp2k.py", line 257, in get_input_string
    input_string = self.CP2K_INPUT._print_input(-1)
  File "/usr/local/lib/python3.7/site-packages/pycp2k-0.2.1-py3.7.egg/pycp2k/inputsection.py", line 176, in _print_input
    substring = subsection._print_input(level + 1)
  File "/usr/local/lib/python3.7/site-packages/pycp2k-0.2.1-py3.7.egg/pycp2k/inputsection.py", line 168, in _print_input
    substring = value._print_input(level + 1)
  File "/usr/local/lib/python3.7/site-packages/pycp2k-0.2.1-py3.7.egg/pycp2k/inputsection.py", line 168, in _print_input
    substring = value._print_input(level + 1)
  File "/usr/local/lib/python3.7/site-packages/pycp2k-0.2.1-py3.7.egg/pycp2k/inputsection.py", line 168, in _print_input
    substring = value._print_input(level + 1)
AttributeError: 'str' object has no attribute '_print_input'

**Comment by lauri-codes** [comment]
Hi @Greenlobby,

The problem is in the line:
```python
DFT.XC.XC_FUNCTIONAL = "BLYP"
```
This is replacing the entire XC_FUNCTIONAL **section** (all section have fully capitalized names) with the string "BLYP". Instead you will want to say that the **section parameter** is BLYP by replacing the line with:

```python
DFT.XC.XC_FUNCTIONAL.Section_parameters = "BLYP"
```

In CP2K the parameters that come in the same line as the section opening are called section parameters, and they are set through the Section_parameters-attribute of the section in pycp2k.
```sh
      &XC_FUNCTIONAL BLYP
      &END XC_FUNCTIONAL
```

Hope this helps!

**Comment by Greenlobby** [comment]
Thanks . it works now . I run the input ,it can generate an cp2k format input file.  Thank you very much  again. 
I have another question . I compared the generated input file with the original input file , the difference is  CELL. Abc unit , how can I insert the unit in python format input ?
---------------------------------------------------------
The original input :
----------------------------------------------------------
@SET SYSTEM run-1H2O-GOPT

@SET LIBDIR /home/dell/Desktop/Link to Softrun/cp2k-6.1/data

&GLOBAL

     PROJECT ${SYSTEM}          # Name of calculation: run-1H2O-GOPT 
     RUN_TYPE GEO_OPT           # Perform a geometry optimization
     PRINT_LEVEL LOW            # Do not output too much information

&END GLOBAL
    
&FORCE_EVAL

     METHOD QuickStep
     &DFT                       # Use density functional theory
        BASIS_SET_FILE_NAME ${LIBDIR}/GTH_BASIS_SETS
        POTENTIAL_FILE_NAME ${LIBDIR}/GTH_POTENTIALS
        &MGRID
             CUTOFF 250    # plane-wave cutoff for the charge density [Rydbergs]
        &END MGRID  
        &SCF                     
             EPS_SCF 1.0E-6         # convergence threshold for total energy
        &END SCF
        &XC    # parameters for exchange-correlation functional
             &XC_FUNCTIONAL BLYP
             &END XC_FUNCTIONAL
             &XC_GRID # some tricks to speed up the calculation of the xc potential
                                                                                                   XC_DERIV       SPLINE2_smooth
                   XC_SMOOTH_RHO  NN10
                                                                                              &END XC_GRID
          &END XC
     &END DFT
                                                                                     &SUBSYS
          &CELL   # box containing the molecule: 15x15x15 Angstroms
            ABC [angstrom] 15 15 15
          &END CELL
          &COORD  # coordinates of the atoms in the box [Angstroms]
               O  0 0 0
               H  0.7 0.7 0
               H -0.7 0.7 0
          &END COORD
          &KIND H # basis sets and pseudo-potentials for atomic species
               BASIS_SET TZVP-GTH
               POTENTIAL GTH-BLYP-q1
          &END KIND
          &KIND O
               BASIS_SET TZVP-GTH
               POTENTIAL GTH-BLYP-q6
          &END KIND
     &END SUBSYS
                          
-----------------------------------------------------------------------------------------------
The generated input :
-----------------------------------------------------
&GLOBAL
  PRINT_LEVEL LOW
  PROJECT_NAME H2O_py3
  RUN_TYPE GEO_OPT
&END GLOBAL
&FORCE_EVAL
  METHOD QuickStep
  &SUBSYS
    &CELL
      ABC 15.0 15.0 15.0
    &END CELL
    &COORD
      O 0 0 0
      H 0.7 0.7 0
      H -0.7 0.7 0
    &END COORD
    &KIND H
      POTENTIAL GTH-BLYP-q1
      BASIS_SET TZVP-GTH
    &END KIND
    &KIND O
      POTENTIAL GTH-BLYP-q6
      BASIS_SET TZVP-GTH
    &END KIND
  &END SUBSYS
  &DFT
    POTENTIAL_FILE_NAME /home/dell/Softrun/cp2k-6.1/GTH_POTENTIALS
    BASIS_SET_FILE_NAME /home/dell/Softrun/cp2k-6.1/GTH_BASIS_SETS
    &MGRID
      CUTOFF 250
    &END MGRID
    &XC
      &XC_FUNCTIONAL BLYP
      &END XC_FUNCTIONAL
      &XC_GRID
        XC_SMOOTH_RHO NN10
      &END XC_GRID
    &END XC
    &SCF
      EPS_SCF 1e-06
    &END SCF
  &END DFT
&END FORCE_EVAL
