### ISSUE TITLE
I have three problems that need your help urgently!!!!!

### ISSUE THREAD

**Issue by Greenlobby** [SINGROUP/pycp2k#7]
I hope to translate the following cp2k scripts into Python format.  I have three problems:
(1) I can not find the corresponding PYTHON INPUTS to replace " COMPONENTS_TO_FIX XYZ" in the CONSTRAINT SECTION;
(2) cp2k inputs can use COSTUM units such as "  ABC [angstrom] 9.1 12.0 17.8" in the CELL SECTION, how can I use PYTHON FORMAT  INPUT to declare CUSTOM UNITS?
(3)I do not why PYTHON FORMAT can not run when I add "calc.write_input_file()"?

The following is my PYTHON FORMAT INPUTS:
-------------------------------------------------------------------------------
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan  3 16:47:06 2020

@author: dell
"""

import  ase

from pycp2k import CP2K

#============================================================
# Setup calculator
calc = CP2K()
calc.working_directory = "./"
calc.project_name = "Al2O3_py_1"
calc.mpi_n_processes = 4

#===============================================================
# Create shortcuts for the most used subtrees of the input.
CP2K_INPUT = calc.CP2K_INPUT
GLOBAL = CP2K_INPUT.GLOBAL
FORCE_EVAL = CP2K_INPUT.FORCE_EVAL_add()
SUBSYS = FORCE_EVAL.SUBSYS
MOTION = CP2K_INPUT.MOTION
DFT = FORCE_EVAL.DFT
FORCEFIELD = FORCE_EVAL.MM.FORCEFIELD

GLOBAL.Run_type = "GEO_OPT"
GLOBAL.Print_level = "LOW"

FORCE_EVAL.Method = "QuickStep"

DFT.Basis_set_file_name = "/home/dell/Softrun/cp2k-6.1/data/BASIS_MOLOPT"
DFT.Potential_file_name = "/home/dell/Softrun/cp2k-6.1/data/GTH_POTENTIALS"
DFT.MGRID.Cutoff = 250
DFT.MGRID.Ngrids = 4
DFT.MGRID.Rel_cutoff = 40
DFT.SCF.Eps_scf = 1.0E-6
DFT.XC.XC_FUNCTIONAL.Section_parameters = "BLYP"
DFT.XC.XC_GRID.Xc_smooth_rho = "NN10"

DFT.SCF.Scf_guess = "ATOMIC"
DFT.SCF.Eps_scf =  1.0E-06
DFT.SCF.Max_scf =  300

OT = DFT.SCF.OT
OT.Minimizer = "DIIS"
OT.Preconditioner = "FULL_ALL"
         
DFT.SCF.OUTER_SCF.Eps_scf =  1.0E-06
DFT.SCF.OUTER_SCF.Max_scf =  30   

#DFT.SCF.PRINT.RESTART = "OFF"     

SUBSYS.COORD.Unit = "angstrom"
SUBSYS.CELL.Abc = [9.1,12.0,17.8]  #how to use CUSTOM UNITS?

SUBSYS.COORD.Default_keyword = [\
                 ["O", 5.72813,11.98165,8.24775],\
                 ["O", 8.10763,7.86025,8.24775],\
                 ["O", 5.72813, 6.48642, 12.57804],\
    ["O", 8.10763,10.60782,12.57804],\
    ["O", 5.72813, 9.23408, 16.90846],\
    ["O", 8.10763, 5.11268, 16.90846],\
    ["O", 5.72813, 6.26115, 8.24775],\
    ["O", 8.10763, 10.38255, 8.24775],\
    ["O", 5.72813, 9.00872, 12.57804],\
    ["O", 8.10763, 13.13012, 12.57804],\
    ["O", 5.72813, 11.75638, 16.90846],\
["O", 8.10763, 7.63498, 16.90846],\
["O", 5.92325, 9.1214, 8.24775],\
["O",8.30275, 5, 8.24775],\
["O", 5.92325, 11.86897, 12.57804],\
["O", 8.30275, 7.74757, 12.57804],\
["O", 5.92325, 6.37383, 16.90846],\
["O", 8.30275, 10.49523, 16.90846],\
["O", 6.65137, 10.38255, 14.74325],\
["O", 9.03087, 6.26115, 14.74325],\
["O", 6.65137, 13.13012, 6.08254],\
["O", 9.03087, 9.00872, 6.08254],\
["O", 6.65137, 7.63498, 10.41296],\
["O", 9.03087, 11.75638, 10.41296],\
["O", 6.65137, 7.86025, 14.74325],\
["O", 9.03087, 11.98165, 14.74325],\
["O", 6.65137, 10.60782, 6.08254],\
["O", 9.03087, 6.48642, 6.08254],\
["O", 6.65137, 5.11268, 10.41296],\
["O", 9.03087, 9.23408, 10.41296],\
["O", 6.45625, 13.2428, 14.74325],\
["O", 8.83575, 9.1214,14.74325],\
["O", 6.45625,	7.74757, 6.08254],\
["O", 8.83575, 11.86897, 6.08254],\
["O", 6.45625, 10.49523, 10.41296],\
["O", 8.83575, 6.37383, 10.41296],\
["Al",5, 5, 9.57283],\
["Al", 7.3795, 9.1214, 9.57283],\
["Al", 5, 7.74757, 13.90312],\
["Al", 7.3795, 11.86897, 13.90312],\
["Al", 5, 10.49523, 5.24254],\
["Al", 7.3795, 6.37383, 5.24254],\
["Al", 5, 5, 6.92267],\
["Al", 7.3795, 9.1214, 6.92267],\
["Al", 5, 7.74757, 11.25296],\
["Al", 7.3795, 11.86897, 11.25296],\
["Al ",5, 10.49523, 15.58338],\
["Al", 7.3795, 6.37383, 15.58338],\
["Al", 5, 5, 13.41817],\
["Al", 7.3795, 9.1214, 13.41817],\
["Al", 5, 7.74757, 17.74846],\
["Al", 7.3795, 11.86897, 17.74846],\
["Al", 5, 10.49523, 9.08788],\
["Al", 7.3795, 6.37383, 9.08788],\
["Al", 5, 5, 16.06833],\
["Al", 7.3795, 9.1214, 16.06833],\
["Al", 5, 7.74757, 7.40762],\
["Al", 7.3795, 11.86897, 7.40762],\
["Al", 5, 10.49523, 11.73804],\
["Al", 7.3795, 6.37383, 11.73804]
        ]

h_kind = SUBSYS.KIND_add("O")
h_kind.Basis_set = "DZVP-MOLOPT-SR-GTH"
h_kind.Potential = "GTH-BLYP-q6"

h_kind =SUBSYS.KIND_add("Al")
h_kind.Basis_set =  "DZVP-MOLOPT-SR-GTH"
h_kind.Potential = "GTH-BLYP-q3"

GEO_OPT = MOTION.GEO_OPT

GEO_OPT.Type = "MINIMIZATION"
GEO_OPT.Max_dr = 1.0E-03
GEO_OPT.Max_force = 1.0E-03
GEO_OPT.Rms_dr = 1.0E-03
GEO_OPT.Rms_force = 1.0E-03
GEO_OPT.Optimizer = "LBFGS"

CONSTRAINT = MOTION.CONSTRAINT
#CONSTRAINT....... = "XYZ"   //How to express: COMPONENTS_TO_FIX XYZ
CONSTRAINT.FIXED_ATOMS_list = 1

#calc.write_input_file()    //When I add this line ,it can not RUN,why?

calc.run()

==========================================================
========================================================

ORGINAL CP2K  INPUTS:
-------------------------------------------------------------------------------
&GLOBAL
  PROJECT Al2O3_1
  RUN_TYPE GEO_OPT
  PRINT_LEVEL LOW
&END GLOBAL
&FORCE_EVAL
  METHOD QS
  &SUBSYS
    &CELL
      ABC [angstrom] 9.1 12.0 17.8
    &END CELL
    &COORD
    O 5.72813 11.98165 8.24775
    O 8.10763 7.86025 8.24775
    O 5.72813 6.48642 12.57804
    O 8.10763 10.60782 12.57804
    O 5.72813 9.23408 16.90846
    O 8.10763 5.11268 16.90846
    O 5.72813 6.26115 8.24775
    O 8.10763 10.38255 8.24775
    O 5.72813 9.00872 12.57804
    O 8.10763 13.13012 12.57804
    O 5.72813 11.75638 16.90846
O 8.10763 7.63498 16.90846
O 5.92325 9.1214 8.24775
O 8.30275 5 8.24775
O 5.92325 11.86897 12.57804
O 8 .30275 7.74757 12.57804
O 5.92325 6.37383 16.90846
O 8.30275 10.49523 16.90846
O 6.65137 10.38255 14.74325
O 9.03087 6.26115 14.74325
O 6.65137 13.13012 6.08254
O 9.03087 9.00872 6.08254
O 6.65137 7.63498 10.41296
O 9.03087 11.75638 10.41296
O 6.65137 7.86025 14.74325
O 9.03087 11.98165 14.74325
O 6.65137 10.60782 6.08254
O 9.03087 6.48642 6.08254
O 6.65137 5.11268 10.41296
O 9.03087 9.23408 10.41296
O 6.45625 13.2428 14.74325
O 8.83575 9.1214 14.74325
O 6.45625	7.74757	6.08254
O 8.83575 11.86897 6.08254
O 6.45625 10.49523 10.41296
O 8.83575 6.37383 10.41296
Al 5 5 9.57283
Al 7.3795 9.1214 9.57283
Al 5 7.74757 13.90312
Al 7.3795 11.86897 13.90312
Al 5 10.49523 5.24254
Al 7.3795 6.37383 5.24254
Al 5 5 6.92267
Al 7.3795 9.1214 6.92267
Al 5 7.74757 11.25296
Al 7.3795 11.86897 11.25296
Al 5 10.49523 15.58338
Al 7.3795 6.37383 15.58338
Al 5 5 13.41817
Al 7.3795 9.1214 13.41817
Al 5 7.74757 17.74846
Al 7.3795 11.86897 17.74846
Al 5 10.49523 9.08788
Al 7.3795 6.37383 9.08788
Al 5 5 16.06833
Al 7.3795 9.1214 16.06833
Al 5 7.74757 7.40762
Al 7.3795 11.86897 7.40762
Al 5 10.49523 11.73804
Al 7.3795 6.37383 11.73804
    
    &END COORD
    &KIND O
     ELEMENT O
      #BASIS_SET DZVP-GTH-PADE
       BASIS_SET DZVP-MOLOPT-SR-GTH
      #POTENTIAL GTH-PADE-q6
       POTENTIAL GTH-BLYP-q6
    &END KIND
    &KIND Al
      ELEMENT	Al
      BASIS_SET DZVP-MOLOPT-SR-GTH
      POTENTIAL GTH-BLYP-q3
    &END KIND
  &END SUBSYS
  &DFT
    BASIS_SET_FILE_NAME BASIS_MOLOPT
    POTENTIAL_FILE_NAME GTH_POTENTIALS
    &QS
      EPS_DEFAULT 1.0E-6
    &END QS
    &MGRID
      CUTOFF 250
      NGRIDS 4
      REL_CUTOFF 40
    &END MGRID
    &SCF
      SCF_GUESS ATOMIC
      EPS_SCF 1.0E-06
      MAX_SCF 300
      &OT
        MINIMIZER DIIS
        PRECONDITIONER FULL_ALL
        #STEPSIZE 0.02 
      &END OT
      &OUTER_SCF
       EPS_SCF 1.0E-06
       MAX_SCF 30
      &END OUTER_SCF
     # &MIXING
      #  METHOD PULAY_MIXING
      #  ALPHA 0.5
       # NPULAY 5
     # &END MIXING
      &PRINT
        &RESTART OFF
        &END RESTART
      &END PRINT
    &END SCF
    &XC
      &XC_FUNCTIONAL BLYP
      &END XC_FUNCTIONAL
    &END XC
  &END DFT
&END FORCE_EVAL
&MOTION
  &GEO_OPT
    TYPE MINIMIZATION
    MAX_DR    1.0E-03
    MAX_FORCE 1.0E-03
    RMS_DR    1.0E-03
    RMS_FORCE 1.0E-03
    MAX_ITER  200
    OPTIMIZER LBFGS 
    #&CG
      #MAX_STEEP_STEPS 0
      #RESTART_LIMIT 9.0E-01
    #&END CG
  &END GEO_OPT
  &CONSTRAINT
    &FIXED_ATOMS
      COMPONENTS_TO_FIX XYZ
      LIST 1
    &END FIXED_ATOMS
  &END CONSTRAINT
&END MOTION

**Comment by Greenlobby** [comment]
I figured out how to use PYTHON INPUTS to replace  " COMPONENTS_TO_FIX XYZ" as followings:
MOTION.FIXED_ATOMS.add().Components_to_fix = "XYZ"

**Comment by lauri-codes** [comment]
Hi  @Greenlobby,

(1) As you mentioned, you will first have to create that section and then add the attributes, like this:
```
CONSTRAINT = MOTION.CONSTRAINT
fix1 = CONSTRAINT.FIXED_ATOMS_add()
fix1.Components_to_fix = "XYZ"
fix1.List = 1
```

(2) You can use any valid strings as section keywords, so just provide the final string like this:
`SUBSYS.CELL.Abc = "[angstrom] " + " ".join([str(x) for x in [9.1, 12.0, 17.8]])
`

(3) I can not reproduce this issue with your input after fixing (1) and (2). Can you elaborate on what error are you getting?
