### ISSUE TITLE
How to use parse?

### ISSUE THREAD

**Issue by Greenlobby** [SINGROUP/pycp2k#8]
I read CP2K.Parse.__doc__, it seems to tell me that "parse" can read the existing CP2K INPUT. so I write some line to test .It goes wrong.

import  ase

from pycp2k import CP2K

#===============================================================================
# Setup calculator
calc = CP2K()
calc.working_directory = "./"
#calc.project_name = "H2O.out"
calc.mpi_n_processes = 4
#calc.input_path = "./"
calc.parse = "H2O_GOPT.inp"

calc.write_input_file()

calc.run()

CP2K INPUT FILE:
===============================================
@SET SYSTEM H2O_GOPT

@SET LIBDIR /home/dell/cp2k-6.1/data

&GLOBAL

     PROJECT ${SYSTEM}          # Name of calculation: run H2O-GOPT 
     RUN_TYPE GEO_OPT           # Perform a geometry optimization
     PRINT_LEVEL LOW            # Do not output too much information

&END GLOBAL
    
&FORCE_EVAL

     METHOD QuickStep
     &DFT                       # Use density functional theory
        BASIS_SET_FILE_NAME ${LIBDIR}/GTH_BASIS_SETS
        POTENTIAL_FILE_NAME ${LIBDIR}/GTH_POTENTIALS
        &MGRID
             CUTOFF 250    # plane-wave cutoff for the charge density [Rydbergs]
        &END MGRID  
        &SCF                     
             EPS_SCF 1.0E-6         # convergence threshold for total energy
        &END SCF
        &XC    # parameters for exchange-correlation functional
             &XC_FUNCTIONAL BLYP
             &END XC_FUNCTIONAL
             &XC_GRID # some tricks to speed up the calculation of the xc potential
                                                                                                   XC_DERIV       SPLINE2_smooth
                   XC_SMOOTH_RHO  NN10
            &END XC_GRID
          &END XC
     &END DFT
                                                                                     &SUBSYS
          &CELL   # box containing the molecule: 15x15x15 Angstroms
            ABC [angstrom] 15 15 15
          &END CELL
          &COORD  # coordinates of the atoms in the box [Angstroms]
               O  0 0 0
               H  0.7 0.7 0
               H -0.7 0.7 0
          &END COORD
          &KIND H # basis sets and pseudo-potentials for atomic species
               BASIS_SET TZVP-GTH
               POTENTIAL GTH-BLYP-q1
          &END KIND
          &KIND O
               BASIS_SET TZVP-GTH
               POTENTIAL GTH-BLYP-q6
          &END KIND
     &END SUBSYS
&END FORCE_EVAL

**Comment by lauri-codes** [comment]
Hi @Greenlobby,

Indeed PYCP2K can parse existing files with the `parse()` function. Just update your line to a proper function call syntax:

`calc.parse("H2O_GOPT.inp")`

and also provide a valid project name:

`calc.project_name = "H2O.out"`

**Comment by charly828** [comment]
First of all I would like to congratulate you for this very nice interface, it's very useful!
I would like to make a documentation suggestion if I may. It took me a bit to guess how to edit a FORCE_EVAL section, read from an already existing file with the calc.parse() method. As it is a repeatable item you cannot access it directly under CP2K_INPUT.  If I got it correctly you have to access it by:

`from pycp2k import CP2K`
`calc = CP2K()`
`calc.parse("template.in")`
`CP2K_INPUT = calc.CP2K_INPUT`
`FORCE_EVAL = CP2K_INPUT.FORCE_EVAL_list[0]`
