### ISSUE TITLE
CalledProcessError: Command 'cp2k.popt -v ' returned non-zero exit status 127.

### ISSUE THREAD

**Issue by Ruskinkot1** [SINGROUP/pycp2k#9]
Got an error during running example_si_cutoff.py
CalledProcessError: Command 'cp2k.popt -v ' returned non-zero exit status 127.

**Comment by LiuGaoyong** [comment]
Hello Ruskinkot1;

This could result from your system cannot find cp2k binary file. Please run "cp2k.popt -v" or "which cp2k.popt" or "find / -name cp2k" to test it.

LiuGaoyong
